// prettier-ignore
const translation = {
    "Global": {
      "Enter": "Ingresar",
      "Submit": "Enviar",
      "NoneYet!": "¡Ninguno todavía!",
      "Cancel": "Cancelar",
      "Save": "Guardar",
      "Confirm": "Confirmar",
      "Accept": "Aceptar",
      "Reject": "Rechazar",
      "NotNow": "No ahora",
      "Share": "Compartir",
      "Decline": "Declinar",
      "Back": "Atrás",
      "Next": "Siguiente",
      "Continue": "Continuar",
      "Info": "Información",
      "ThisDecisionCannotBeChanged.": "Esta decisión no puede ser cambiada.",
      "Failure": "Fallo",
      "Success": "Éxito",
      "SomethingWentWrong": "Algo salió mal",
      "Done": "Hecho",
      "Skip": "Omitir",
      "View": "Ver",
      "Home": "Inicio",
      "ErrorCode": "Error",
      "Okay": "Bien",
      "GoBack": "Regresar",
      "GetStarted": "Comenzar",
      "Dismiss": "Descartar",
      "ShowDetails": "Mostrar detalles",
      "TryAgain": "Intentar de nuevo",
      "Biometrics": "Biométricos",
      "On": "Encendido",
      "Off": "Apagado",
      "Close": "Cerrar",
      "Remove": "Eliminar",
    },
    "Date": {
      "ShortFormat": "MMM D",
      "LongFormat": "MMMM D",
      "MonthLong": {
        "January": "Enero",
        "February": "Febrero",
        "March": "Marzo",
        "April": "Abril",
        "May": "Mayo",
        "June": "Junio",
        "July": "Julio",
        "August": "Agosto",
        "September": "Septiembre",
        "October": "Octubre",
        "November": "Noviembre",
        "December": "Diciembre",
      },
      "MonthShort": {
        "January": "Ene",
        "February": "Feb",
        "March": "Mar",
        "April": "Abr",
        "May": "May",
        "June": "Jun",
        "July": "Jul",
        "August": "Ago",
        "September": "Sep",
        "October": "Oct",
        "November": "Nov",
        "December": "Dic",
      },
      "MinuteAgo": "hace un minuto",
      "MinutesAgo": "Hace unos minutos",
      "JustNow": "Ahora",
    },
    "Language": {
      "code_en": "Inglés",
      "code_fr": "Francés",
      "code_pt-BR": "Portugués",
      "code_sp": "Español",
    },
    "Error": {
      "ReportThisProblem": "Report this problem",
      "Unknown": "Error desconocido",
      "Problem": "Ha ocurrido un problema",
      "ErrorCode": "Error",
      "Title1024": "No se pudo aceptar la oferta de la credencial.",
      "Message1024": "Hubo un problema al aceptar la oferta de la credencial.",
      "Title1025": "No se pudo rechazar la oferta de la credencial",
      "Message1025": "Hubo un problema al rechazar la oferta de la credencial",
      "Title1026": "No se pudieron actualizar las credenciales obtenidas.",
      "Message1026": "Hubo un problema al actualizar las credenciales obtenidas.",
      "Title1027": "No se pudo aceptar la solicitud de prueba.",
      "Message1027": "Hubo un problema al aceptar la solicitud de prueba.",
      "Title1028": "No se pudo rechazar la solicitud de prueba",
      "Message1028": "Hubo un problema al rechazar la solicitud de prueba",
      "Title1029": "Los Detalles no pudieron actualizar las credenciales obtenidas.",
      "Message1029": "Hubo un problema al actualizar las credenciales obtenidas.",
      "Title1030": "No se pudo aceptar la conexión.",
      "Message1030": "Hubo un problema al aceptar la redirección de la conexión.",
      "Title1031": "No se pudo aceptar la conexión.",
      "Message1031": "Hubo un problema al aceptar la conexión.",
    "Title1032": "No se pudo eliminar la credencial.",
    "Message1032": "Hubo un problema al eliminar la credencial.",
    "Title1033": "No se pudo obtener la credencial.",
    "Message1033": "La credencial no pudo ser encontrada.",
    "Title1034": "No se pudo obtener la solicitud de prueba.",
    "Message1034": "La solicitud de prueba no pudo ser encontrada.",
    "Title1035": "No se pudo obtener la oferta de la credencial.",
    "Message1035": "La oferta de la credencial no pudo ser encontrada.",
    "Title1036": "No se pudieron obtener las credenciales de la billetera",
    "Message1036": "Las credenciales de la billetera no pudieron ser encontradas",
    "Title1037": "No se pudo eliminar el Contacto.",
    "Message1037": "Hubo un problema al eliminar el Contacto.",
    "Title1038": "No se pudo generar una solicitud de prueba.",
    "Message1038": "Hubo un problema al generar una solicitud de prueba.",
    "Title1039": "No se pudo manejar el enlace profundo.",
    "Message1039": "Hubo un problema al manejar el enlace profundo.",
    "Title1040": "No se pudo crear la contraseña.",
    "Message1040": "Hubo un problema al crear la contraseña.",
    "Title1041": "No se pudo desbloquear con la contraseña.",
    "Message1041": "Hubo un problema al desbloquear con la contraseña.",
    "Title1042": "No se pudo verificar la contraseña.",
    "Message1042": "Hubo un problema al verificar la contraseña.",
    "Title1043": "No se pudieron recuperar las credenciales para la prueba.",
    "Message1043": "Hubo un problema al recuperar las credenciales para la prueba.",
    "Title1044": "No se pudo iniciar el proceso de incorporación.",
    "Message1044": "Hubo un problema al iniciar el proceso de incorporación.",
    "Title1045": "No se pudo iniciar el agente.",
    "Message1045": "Hubo un problema al iniciar el agente.",
  },
  "ActivityLog": {
    "Your": "Tú",
    "Activity": "registro de actividad",
    "Updated": "ha sido actualizado",
  },
  "StatusMessages": {
    "InitAgent": "Iniciando el agente ..."
  },
  "Terms": {
    "TermsOfService": "Términos de Servicio",
    "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
    "IAgree": "Estoy de acuerdo",
    "Attestation": "He leído, comprendido y acepto los términos y condiciones.",
  },
  "Tour": {
    "GuideTitle": "Bienvenido a DigiCred Wallet",
    "WouldYouLike": "¿Le gustaría recibir orientación sobre cómo usar DigiCred Wallet?",
    "UseAppGuides": "Usar las guías de la aplicación",
    "DoNotUseAppGuides": "No usar las guías de la aplicación",
    "AddAndShare": "Agregar y compartir las credenciales",
    "AddAndShareDescription": "Para agregar y usar las credenciales, escanea el código QR mostrado por el proveedor del servicio.",
    "AddCredentials": "Agregar las credenciales",
    "AddCredentialsDescription": "Agregue las credenciales escaneando el código QR mostrado en el servicio emisor.",
    "Notifications": "Notificaciones",
    "NotificationsDescription": "Después de escanear el código QR, la oferta de la credencial o la solicitud de prueba aparecerá aquí, así como otros eventos notables.",
    "YourCredentials": "Tus credenciales",
    "YourCredentialsDescription": "Tus credenciales digitales agregadas aparecen aquí. Puedes revisar los detalles de las credenciales y agregar y eliminar credenciales.",
    "CredentialOffers": "Ofertas de las credenciales",
    "CredentialOffersDescription": "Una organización te ha ofrecido una credencial. Revisa los detalles de las credenciales y elija aceptarla o rechazarla. Las credenciales aceptadas se agregarán a tu billetera.",
    "ProofRequests": "Solicitudes de prueba",
    "ProofRequestsDescription": "Una organización te está pidiendo que solicitud de prueba de tus credenciales. Revisa lo que están pidiendo y elija aceptarla o rechazarla.",
    "Skip": "Omitir",
    "Next": "Siguiente",
    "Back": "Atrás",
    "Done": "Hecho",
  },
  // *ACS* - changed to DigiCred
  "CameraDisclosure": {
    "AllowCameraUse": "Permitir el uso de la cámara",
    "CameraDisclosure": "La cámara se utiliza para escanear códigos QR que inician una oferta de la credencial o una solicitud de la credencial. No se almacena información sobre las imágenes, se usa para análisis o se comparte.",
    "ToContinueUsing": "Para continuar usando la función de escaneo de DigiCred Wallet, por favor, permita los permisos de cámara.",
    "OpenSettings": "Abrir configuraciones",
  },
  "contraseñaCreate": {
    "Message": {
      "CrossPatternValidation": "Se detectó un patrón de cruz en tu contraseña. Inténtelo de nuevo.",
      "OddOrEvenSequenceValidation": "Se detectó una secuencia de números pares o impares en tu contraseña. Inténtelo de nuevo.",
      "NoRepetitionOfTheSameNumbersValidation": "la contraseña no puede tener una repetición del mismo dígito. Inténtelo de nuevo.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Se detectó una secuencia repetida de dos dígitos en tu contraseña. Inténtelo de nuevo.",
      "NoSeriesOfNumbersValidation": "Se detectó una serie en tu contraseña. Inténtelo de nuevo.",
      "contraseñaOnlyContainDigitsValidation": "Tu contraseña solo debe contener dígitos. Inténtelo de nuevo.",
      "contraseñaTooShortValidation": "Tu contraseña es demasiado corta. Inténtelo de nuevo.",
      "contraseñaTooLongValidation": "Tu contraseña es demasiado larga. Inténtelo de nuevo.",
      "OldcontraseñaIncorrect": "Tu antigua contraseña es incorrecta. Inténtelo de nuevo."
    },
    "Helper": {
      "CrossPatternValidation": "No debe contener un patrón de cruz.",
      "OddOrEvenSequenceValidation": "No debe contener una secuencia de números pares o impares.",
      "NoRepetitionOfTheSameNumbersValidation": "No debe contener el mismo número repetido.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "No debe contener una secuencia repetida de dos dígitos.",
      "NoSeriesOfNumbersValidation": "No debe contener una serie de números (123).",
      "contraseñaOnlyContainDigitsValidation": "Debe contener solo dígitos.",
      "contraseñaTooShortValidation": "la contraseña es muy corta.",
      "contraseñaTooLongValidation": "la contraseña es muy larga.",
    },
    "UserAuthenticationcontraseña": "contraseña de autenticación de usuario",
    "contraseñaTooShort": "la contraseña es demasiado corta",
    "Invalidcontraseña": "contraseña inválida",
    "contraseñasDoNotMatch": "Las contraseñas no coinciden",
    "PleaseUseOnlyNumbersInYourcontraseña": "Por favor, usa solo números en tu contraseña",
    "YourcontraseñaMustBe6DigitsInLength": "Tu contraseña debe tener 6 dígitos de longitud.",
    "EnteredcontraseñasDoNotMatch": "Los digitos ingresados en la contraseña no coinciden. Inténtelo de nuevo.",
    "YouNeedToCreateA6Digitcontraseña": "Necesita crear una contraseña de 6 dígitos",
    "PleaseReenterYourcontraseña": "Por favor,introduce tu contraseña nuevamente",
    "contraseñaChangeSuccessTitle": "Cambiaste tu contraseña exitosamente",
    "contraseñaChangeSuccessMessage": "Tu contraseña ha sido cambiado exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.",
    "EnterOldcontraseñaTitle": "Ingresa tu antigua contraseña",
    "Newcontraseña": "nuevo",
    "EntercontraseñaTitle": "Ingresa una contraseña de {{ new }}6 dígitos",
    "Entercontraseña": "Ingresa la contraseña",
    "Reentercontraseña": "Reintroduzca la {{ new }}contraseña",
    "ReentercontraseñaTitle": "Ingresa la contraseña nuevamente",
    "Createcontraseña": "Crear contraseña",
    "Remembercontraseña": "Crea una contraseña para asegurar tu billetera.",
    "RememberChangecontraseña": "Cambia tu contraseña para asegurar tu billetera.",
    "contraseñaDisclaimer": "Si olvidas tu contraseña, es posible que necesites configurar tu billetera nuevamente y volver a agregar tus tarjetas.",
    "Show": "Mostrar contraseña",
    "Hide": "Ocultar contraseña",
    "Changecontraseña": "Cambiar contraseña",
    "Continue": "Continuar",
    "EnterYourCurrentcontraseña": "Ingresa tu contraseña actual"
  },
  "contraseñaEnter": {
    "Entercontraseña": "Ingresa la contraseña de tu billetera",
    "Unlock": "Desbloquear",
    "Or": "O",
    "BiometricsUnlock": "Desbloquear con Biométricos",
    "Incorrectcontraseña": "contraseña incorrecta",
    "Repeatcontraseña": "Intenta tu contraseña nuevamente.",
    "EnableBiometrics": "Debe habilitar los Biométricos para poder cargar la billetera.",
    "BiometricsNotProvided": "No se proporcionó Biométricos, puedes usar tu contraseña para cargar la billetera.",
    "BiometricsError": "Los Biométricos no fueron exitosos.",
    "BiometricsErrorEntercontraseña": "Por favor, ingrese la contraseña de tu billetera.",
    "LoggedOut": "Ha cerrado sesión",
    "LoggedOutDescription": "Para proteger tu información, se cerrará la sesión en tu billetera si no la has utilizado durante 5 minutos.",
    "BiometricsChanged": "El desbloqueo con Biométricos ha sido deshabilitado porque los Biométricos de tu dispositivo han cambiado.",
    "BiometricsChangedEntercontraseña": "Por favor, ingresa tu contraseña de billetera.",
    "AttemptLockoutWarning": "Nota: por tu seguridad, si ingresas otra contraseña incorrecta el sistema bloqueará temporalmente tu billetera."
  },
  "AttemptLockout": {
    "Title": "Tu billetera está temporalmente bloqueada",
    "Description": "Has tenido demasiados intentos fallidos de contraseña.",
    "TryAgain": "Puedes intentarlo de nuevo en:",
    "Hours": "horas",
    "Minutes": "minutos",
    "Seconds": "segundos"
  },
  "Biometry": {
    "Toggle": "Alternar Biométricos",
    "EnabledText1": "Desbloquea la billetera con los Biométricos de tu teléfono en lugar de tu contraseña.",
    "EnabledText2": "Usar Biométricos significa que todas las huellas dactilares o reconocimiento facial agregados en este teléfono tendrán acceso a tu billetera.",
    "NotEnabledText1": "Los Biométricos no están configurados actualmente en este dispositivo y, por lo tanto, no se puede activar.",
    "NotEnabledText2": "Si deseas activar esta característica, activa los Biométricos en los ajustes del dispositivo y luego regresa a esta pantalla.",
    "Warning": "Asegúrate de que solo tú tengas acceso a tu billetera.",
    "UseToUnlock": "¿Desea usar Biométricos para desbloquear la billetera?",
    "UnlockPromptTitle": "Desbloqueo de la billetera",
    "UnlockPromptDescription": "Usa los Biométricos para desbloquear tu billetera"
  },
  "Contacts": {
    "EmptyList": "¡Tu lista de Contactos está vacía!",
    "TypeHere": "Escribe un mensaje a este contacto...",
    "PeopleAndOrganizations": "Las personas y organizaciones con las que has interactuado aparecen aquí.",
    "WhatAreContacts": "¿Qué son los Contactos?",
    "AddContact": "Agregar Contacto",
  },
  "ContactDetails": {
    "Created": "Creado",
    "ConnectionState": "Estado de la conexión",
    "AContact": "Un Contacto",
    "DateOfConnection": "Conectado: {{ date }}",
    "RemoveTitle": "Eliminar este Contacto",
    "RemoveCaption": "Para agregar las credenciales, la organización emisora necesita ser un Contacto.",
    "UnableToRemoveTitle": "No se puede eliminar el Contacto",
    "UnableToRemoveCaption": "No se puede eliminar porque hay credenciales emitidas por este Contacto en tu billetera. Elimina primero las credenciales y luego el Contacto.",
    "GoToCredentials": "Ir a las Credenciales",
    "RemoveContact": "Eliminar Contacto",
    "ContactRemoved": "Contacto eliminado",
    "RemoveContactMessageTop": "Al eliminar este Contacto ya no podrás:",
    "RemoveContactMessageBottom": "Este Contacto no será notificado de que lo has eliminado de tus Contactos",
    "RemoveContactsBulletPoint1": "Enviar mensajes directos a este Contacto",
    "RemoveContactsBulletPoint2": "Recibir nuevas credenciales de este Contacto",
    "RemoveContactsBulletPoint3": "Recibir notificaciones de actualizaciones de tus credenciales emitidas por este Contacto",
    "RemoveContactsBulletPoint4": "Solicitar información de este Contacto o que él te la solicite a ti",
  },
  "WhatAreContacts": {
    "Title": "¿Qué son los Contactos?",
    "Preamble": "Los Contactos son personas u organizaciones con las que has interactuado.\n\nEstás conectado mediante una línea segura y privada que solo tú o ellos pueden ver. Nada se comparte sin tu permiso.\n\nPuedes:",
    "ListItemDirectMessage": "Enviar mensajes directos a tus Contactos",
    "ListItemNewCredentials": "Recibir nuevas credenciales",
    "ListItemNotifiedOfUpdates": "Recibir notificaciones de actualizaciones a tus credenciales emitidas por tus contactos",
    "ListItemRequest": "Solicitar información de tu Contacto o que ellos te la soliciten a ti",
    "RemoveContacts": "Puedes eliminar tus Contactos en cualquier momento",
    "ContactsLink": "lista de Contactos",
  },
  "Credentials": {
    "CredentialsNotFound": "Credenciales no encontradas",
    "CredentialDetails": "Detalles de la credencial",
    "EmptyList": "Tu billetera está vacía. Tus credenciales aceptadas se agregarán aquí.",
    "IssuedBy": "Emitido por",
    "Credential": "credencial"
  },
  "PushNotifications": {
    "EnableNotifiactions": "Habilita Notificaciones para recibir alertas instantáneas",
    "BeNotified": "Ser notificado cuando recibas:",
    "ReceiveNotifications": "Recibir notificaciones",
    "BulletFour": "nuevos mensajes",
    "BulletOne": "nuevas ofertas de credenciales",
    "BulletThree": "actualizaciones a tus credenciales",
    "BulletTwo": "nuevas solicitudes de prueba",
    "NotificationsOffMessage": "Ser notificado cuando recibas nuevas ofertas de credenciales, solicitudes de prueba, actualizaciones a tus credenciales, nuevos mensajes y más.",
    "NotificationsOffTitle": "Las notificaciones para Bifold están desactivadas",
    "NotificationsInstructionTitle": "Para habilitar las notificaciones:",
    "InstructionsOne": "Abre los ajustes de la aplicación",
    "InstructionsTwo": "Toca Notificaciones",
    "InstructionsThree": "Habilita las notificaciones",
    "OpenSettings": "Abrir configuración",
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Creado el:",
    "Version": "Versión",
    "Issued": "Emitido",
    "PrivacyPolicy": "Política de privacidad",
    "TermsAndConditions": "Términos y condiciones",
    "RemoveFromWallet": "Eliminar de la billetera",
    "Revoked": "Revocado",
    "CredentialRevokedMessageTitle": "Esta credencial ha sido revocada",
    "CredentialRevokedMessageBody": "Esta credencial puede que ya no funcione para algunas solicitudes de prueba. Necesitarás actualizar la credencial con el emisor.",
    "NewRevoked": "Credencial revocada",
    "RemoveTitle": "Eliminar la credencial de tu billetera",
    "RemoveCaption": "Perderás la capacidad de probar la información de esta credencial con esta billetera.",
    "CredentialNotFound": "Credencial no encontrada",
    "YouWillNotLose": "No perderás",
    "YouWillNotLoseListItem1": "Tu credencial está dentro del sistema que emitió la misma.",
    "YouWillNotLoseListItem2": "La organización emisora como un Contacto.",
    "HowToGetThisCredentialBack": "Cómo recuperar esta credencial",
    "HowToGetThisCredentialBackListItem1": "Tendrás que ir a la organización que te emitió esta credencial y solicitarla de nuevo.",
    "CredentialRemoved": "Credencial eliminada",
    "IssuedBy": "Emitido por:",
    "RemoveCredential": "Eliminar Credencial",
  },
  "Home": {
    "Welcome": "Bienvenido",
    "Notification": "Notificación",
    "Notifications": "Inicio",
    "NoNewUpdates": "No tienes nuevas notificaciones.",
    "NoCredentials": "No tienes credenciales en tu billetera.",
    "SeeAll": "Ver todo",
    "YouHave": "Tienes",
    "Credential": "credencial",
    "Credentials": "credenciales",
    "InYourWallet": "en tu billetera",
    "NewMessage": "Nuevo mensaje",
    "SentMessage": "envió un mensaje",
    "ReceivedMessage": "Has recibido un nuevo mensaje",
    "ViewMessage": "Ver mensaje",
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Conexión aceptada con éxito",
    "AcceptingConnection": "Aceptando conexión",
    "ConnectionRecordIdNotFound": "ID de registro de conexión no encontrado",
    "ConnectionAccepted": "Conexión aceptada",
    "ConnectionNotFound": "Conexión no encontrada",
    "InvalidQrCode": "Código QR inválido. Por favor, inténtalo de nuevo.",
    "WillScanAutomatically": "Un código QR válido se escaneará automáticamente.",
    "ScanQRCode": "Escanear código QR",
    "MyQRCode": "Mi código QR",
    "UnableToHandleRedirection": "No se puede redireccionar",
    "Close": "Cerrar",
    "Torch": "Linterna",
    "ScanHelp": "Ayuda para escanear",
    "ScanNow": "Escanear ahora",
    "WhatToScan": "¿Qué códigos QR se pueden escanear?",
    "ScanOnySpecial": "Solo códigos QR especiales pueden ser escaneados por Bifold Wallet.",
    "ScanOnlySpecial2": "Estos son presentados por servicios participantes o personas para recibir una oferta de credencial, solicitud de información o para conectar.",
    "ScanOnlySpecial3": "Bifold Wallet actualmente no permite añadir credenciales digitales escaneando o tomando fotos de una credencial física.",
    "WhereToUseLink": "Ver dónde puedes usar Bifold Wallet",
    "BadQRCode": "Código QR no reconocido",
    "BadQRCodeDescription": "El código QR escaneado no funciona con Bifold Wallet. Bifold Wallet solo funciona con servicios participantes.\n\nActualmente no puede añadir credenciales digitales tomando fotos de unas físicas.",
  },
  "Connection": {
    "JustAMoment": "Solo un momento mientras hacemos una conexión segura...",
    "TakingTooLong": "Esto está tardando más de lo habitual. Puedes volver al inicio o continuar esperando.",
    "ConnectionInvitation": "Invitación de conexión",
    "ScanQR": "Muestra este código QR a la otra persona",
    "ScanQRComment": "Después de que el código QR sea escaneado, se creará una conexión.",
    "ShareQR": "Compartir este código QR con alguien añadirá a esa persona como un Contacto.",
    "MakingConnection": "Creando conexión...",
    "ConnectionCompleted": "¡Conexión completada!",
    "Toggle": "Alternar capacidad de invitación de conexión",
    "UseConnectionInviterCapability": "¿Usar la capacidad de invitador de conexión?",
    "OpenContact": "Abrir Contacto",
  },
  "ConnectionAlert": {
    "AddedContacts": "Añadido a Contactos",
    "WhatAreContacts": "¿Qué son los Contactos?",
    "NotificationBodyUpper": "Puedes encontrar ",
    "NotificationBodyLower": " en tus Contactos. Gestiona tus Contactos en Configuración",
    "Popucontraseñatro": "Añadir organizaciones como Contacto te permitirá:",
    "PopupPoint1": "Recibir actualizaciones de las credenciales emitidas por esta organización",
    "PopupPoint2": "Recibir nuevas credenciales",
    "PopupPoint3": "Agilizar las solicitudes de prueba",
    "SettingsLink": "Configuración",
    "SettingsInstruction": "Los contactos se pueden eliminar en cualquier momento",
    "PrivacyMessage": "El uso de tus credenciales nunca se comparte con tus Contactos.",
    "PopupExit": "Entendido"
  },
  "CredentialOffer": {
    "CredentialOffer": "Oferta de la Credencial",
    "ThisIsTakingLongerThanExpected": "Esto está tomando más tiempo de lo esperado. Vuelve más tarde para ver tu nueva credencial.",
    "RejectThisCredential?": "¿Rechazar esta Credencial?",
    "AcceptingCredential": "Aceptando Credencial",
    "SuccessfullyAcceptedCredential": "Credencial Aceptada Exitosamente",
    "RejectingCredential": "Rechazando Credencial",
    "SuccessfullyRejectedCredential": "Credencial Rechazada Exitosamente",
    "CredentialNotFound": "Credencial no encontrada",
    "CredentialAccepted": "Credencial Aceptada",
    "CredentialRejected": "Credencial Rechazada",
    "CredentialAddedToYourWallet": "Credencial añadida a tu billetera",
    "CredentialDeclined": "Credencial rechazada",
    "CredentialOnTheWay": "Tu credencial está en camino",
    "NewCredentialOffer": "Nueva Oferta de Credencial",
    "IsOfferingYouACredential": "te está ofreciendo una credencial",
    "ConfirmDeclinedTitle": "¿Estás seguro de que quieres rechazar esta credencial?",
    "ConfirmDeclinedMessage": "Para recibir nuevamente la oferta de credencial, necesitarás volver a solicitarla con el emisor.",
    "ConfirmDecline": "Sí, rechazar esta credencial",
    "AbortDecline": "No, volver atrás",
    "DeclineTitle": "¿Rechazar oferta de credencial?",
    "Declined": "Rechazada",
    "DeclineParagraph1": "Para recibir nuevamente la oferta de la credencial, necesitarás reiniciar el proceso de emisión con el servicio emisor.",
    "DeclineParagraph2": "¿Estás seguro de que quieres rechazar esta oferta de credencial?",
    "CustomOfferTitle": "¿Eliminar esta oferta?",
    "CustomOfferParagraph1": "Eliminar esta oferta removerá la notificación de tu lista.",
    "CustomOfferParagraph2": "¿No reconoces a la organización? Revisa tu lista de Contactos. Solo recibirás notificaciones de Contactos que hayas iniciado.",
    "DeleteOfferTitle": "¿Eliminar esta oferta?",
    "DeleteOfferMessage": "Eliminar esta oferta removerá la notificación de tu lista.",
    "DeleteOfferDescription": "¿No reconoces a la organización? Revisa tu lista de Contactos. Solo recibirás notificaciones de Contactos que hayas iniciado."
  },
  "ProofRequest": {
    "JustAMoment": "Un momento mientras preparamos todo para ti...",
    "FromYourWallet": "Desde tu billetera",
    "MissingCredentials": "Faltan credenciales",
    "PredicateGeDate": "es después",
    "PredicateLeDate": "es antes",
    "PredicateGe": "es mayor o igual que",
    "PredicateGr": "es mayor que",
    "PredicateLe": "es menor o igual que",
    "PredicateLs": "es menor que",
    "ProofRequest": "Solicitud de Prueba",
    "RequestProcessing": "Un momento...",
    "OfferDelay": "Retraso de la oferta",
    "ChangeCredential": "Cambiar credencial",
    "GetThisCredential": "Obtener esta credencial",
    "RejectThisProof?": "¿Rechazar esta Solicitud de Prueba?",
    "DeclineThisProof?": "¿Declinar esta Solicitud de Prueba?",
    "MultipleCredentials": "Tienes múltiples credenciales para elegir:",
    "AcceptingProof": "Aceptando Prueba",
    "SuccessfullyAcceptedProof": "Prueba Aceptada Exitosamente",
    "SensitiveInformation": "Esta solicitud está pidiendo información sensible.",
    "ProofRequestNotFound": "Solicitud de Prueba no Encontrada",
    "RejectingProof": "Rechazando Prueba",
    "ProofAccepted": "Prueba Aceptada",
    "ProofRejected": "Prueba Rechazada",
    "RequestedCredentialsCouldNotBeFound": "No se pudieron encontrar las credenciales solicitadas",
    "NewProofRequest": "Nueva Solicitud de Prueba",
    "NotAvailableInYourWallet": "No está en tu billetera",
    "PredicateNotSatisfied": "Requisito no cumplido",
    "IsRequesting": "está solicitando",
    "IsRequestingSomethingYouDontHaveAvailable": "está solicitando algo que no tienes disponible",
    "YouDoNotHaveDataPredicate": "No cumples con los requisitos de esta solicitud de prueba de",
    "IsRequestingYouToShare": "está solicitando que compartas la siguiente información de",
    "Credential": "credencial.",
    "Credentials": "credenciales.",
    "WhichYouCanProvideFrom": "que puedes proporcionar desde",
    "Details": "Detalles",
    "SendingTheInformationSecurely": "Enviando la información de manera segura",
    "InformationSentSuccessfully": "Información enviada exitosamente",
    "NewProof": "Nueva Prueba",
    "ProofRequestDeclined": "Solicitud de Prueba declinada",
    "ConfirmDeclinedTitle": "¿Estás seguro de que quieres declinar esta solicitud de prueba?",
    "ConfirmDeclinedMessage": "Para recibir nuevamente la solicitud de prueba, el solicitante necesitará reenviarla.",
    "ConfirmDecline": "Sí, declinar esta solicitud de prueba",
    "AbortDecline": "No, volver atrás",
    "DeclineTitle": "¿Declinar solicitud de prueba?",
    "Declined": "Declinada",
    "ReviewSentInformation": "Compartiste la siguiente información de {{count}} credenciales con", // this exists to make typescript happy
    "ReviewSentInformation_one": "Compartiste la siguiente información de {{count}} credencial con",
    "ReviewSentInformation_other": "Compartiste la siguiente información de {{count}} credenciales con",
    "ShareFollowingInformation": "está compartiendo la siguiente información de {{count}} credenciales.", // this exists to make typescript happy
    "ShareFollowingInformation_one": "está compartiendo la siguiente información de {{count}} credencial.",
    "ShareFollowingInformation_other": "está compartiendo la siguiente información de {{count}} credenciales.",
    "DeclineBulletPoint1": "Las organizaciones y servicios requieren que pruebes que eres elegible para continuar con tu servicio o acceso.",
    "DeclineBulletPoint2": "Para recibir nuevamente la solicitud de prueba, necesitarás reiniciar el proceso con el servicio.",
    "DeclineBulletPoint3": "¿Estás seguro de que quieres declinar esta solicitud de prueba?",
    "NoInfoShared": "No se compartió información",
    "YourInfo": "Tu información no fue compartida",
  },
  "Settings": {
    "Version": "Versión",
    "VersionString": "0.0.0-0",
    "AppSettings": "Configuración", // *ACS*
    "AboutApp": "Acerca de la aplicación",
    "Changecontraseña": "Cambiar contraseña",
    "Language": "Idioma",
    "DataRetention": "Retención de datos",
    "PreventAutoLock": "Prevenir bloqueo automático",
    "TogglePreventAutoLock": "Alternar prevención de bloqueo automático",
    "AppGuides": "Guías de la aplicación",
    "Build": "Construir",
    "WhatAreContacts": "¿Qué son los Contactos?",
    "ScanMyQR": "Escanear mi código QR",
    "Help": "Ayuda",
    "MoreInformation": "Más información",
    "Developer": "Opciones de desarrollador",
    "Notifications": "Notificaciones",
  },
  "TabStack": {
    "Home": "Inicio",
    "Scan": "Escanear",
    "Credentials": "Credenciales",
    "Conversation": "Conversación",
    "Settings": "Configuración",
    "Contacts": "Contactos",
  },
  "RootStack": {
    "Contacts": "Contactos",
    "Settings": "Configuración"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Permiso para usar la cámara",
    "WeNeedYourPermissionToUseYourCamera": "Necesitamos tu permiso para usar tu cámara",
    "Ok": "Ok",
  },
  "QRRender": {
    "GenerationError": "Incapaz de generar código QR",
  },
  "Record": {
    "Hide": "Ocultar",
    "Show": "Mostrar",
    "HideAll": "Ocultar todo",
    "ShowAll": "Mostrar todo",
    "Hidden": "Oculto",
    "InvalidDate": "Fecha inválida: ",
    "Zoom": "Zoom",
  },
  "Screens": {
    "Splash": "Splash",
    "Onboarding": "Introducción",
    "Preface": "DigiCred Wallet", // *ACS*
    "Terms": "Términos y Condiciones",
    "Createcontraseña": "Crear un contraseña",
    "Entercontraseña": "Ingresar contraseña",
    "Home": "Inicio",
    "Scan": "Escanear",
    "Credentials": "Credenciales",
    "CredentialDetails": "Detalles de la Credencial",
    "Notifications": "Inicio",
    "CredentialOffer": "Oferta de la Credencial",
    "ProofChangeCredential": "Elegir una credencial",
    "ProofRequest": "Solicitud de Prueba",
    "ProofRequestDetails": "Detalles de la Solicitud de Prueba",
    "ProofRequestAttributeDetails": "Detalles de los Atributos de la Solicitud de Prueba",
    "ProofDetails": "Detalles de la Prueba",
    "Settings": "Configuración",
    "Tours": "Guías de la aplicación",
    "Language": "Idioma",
    "DataRetention": "Retención de datos",
    "Contacts": "Contactos",
    "Decline": "Rechazar",
    "ContactDetails": "Detalles del Contacto",
    "Biometry": "Biométricos",
    "Developer": "Opciones de desarrollador",
    "Changecontraseña": "Cambiar contraseña",
    "CommonDecline": "Rechazar",
    "ProofRequests": "Solicitudes de Prueba",
    "SendProofRequest": "Enviar una Solicitud de Prueba",
    "ChooseProofRequest": "Elegir una Solicitud de Prueba",
    "ProofRequestUsageHistory": "Historial de Uso",
    "CreateConnectionInvitation": "Crear una Invitación de Conexión",
    "AttemptLockout": "Bloqueo Temporal",
    "OnTheWay": 'En Camino',
    "Declined": 'Rechazado',
    "UseBiometry": 'Usar Biométricos',
    "UsePushNotifications": 'Usar Notificaciones prestablecidas',
    "CustomNotification": 'Notificación Personalizada',
    "ProofRequesting": 'Solicitando Prueba',
    "NameWallet": "Nombrar tu billetera",
    "RenameContact": "Editar Nombre del Contacto",
    "FindAndConnectOpportunities": "Buscar y Conectar Oportunidades",
    "EducationList": "Educación",
    "InstitutionDetail": "Detalles de la Institución",
    "MilitaryList": "Militar",
    "EmployersList": "Empleadores",
    "StateGovernmentList": "Gobierno Estatal",
  },
  "Loading": {
    "TakingTooLong": "Esto está tomando más tiempo de lo usual. Puedes volver al inicio o seguir esperando.",
    "BackToHome": "Volver al inicio"
  },
  "NameWallet": {
    "EnableWalletNaming": "Habilitar el nombre de la billetera?",
    "ToggleWalletNaming": "Cambiar el nombre de la billetera",
    "NameYourWallet": "Nombra la billetera",
    "EditWalletName": "Editar nombre de la billetera",
    "ThisIsTheName": "Este es el nombre que la gente verá cuando se conecte contigo.",
    "CharCountTitle": "Límite de caracteres excedido",
    "CharCountDescription": "Has excedido el límite máximo de 50 caracteres. Por favor, reduce el número de caracteres.",
    "EmptyNameTitle": "El nombre de la billetera no puede estar vacío",
    "EmptyNameDescription": "Este es el nombre que la gente verá cuando se conecte contigo.\n\nPor favor, introduce un nombre para la billetera.",
  },
  "RenameContact": {
    "ThisContactName": "Este nombre de contacto solo se mostrará en tu Lista de Contactos.",
    "ContactName": "Nombre del contacto",
    "CharCountTitle": "Límite de caracteres excedido",
    "CharCountDescription": "Has excedido el límite máximo de 50 caracteres. Por favor, reduce el número de caracteres.",
    "EmptyNameTitle": "El nombre del contacto no puede estar vacío",
    "EmptyNameDescription": "Este es el nombre que verás para este Contacto en tu lista de Contactos.\n\nPor favor, introduce un nombre para el contacto.",
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "Sin conexión a Internet",
    "NoInternetConnectionMessage": "No podrás acceder a los servicios usando Bifold o recibir credenciales hasta que estés en línea.\n\nPor favor, verifica tu conexión a internet.",
    "LedgerConnectivityIssueTitle": "Servicios de la Billetera",
    "LedgerConnectivityIssueMessage": "Un sistema diseñado para proteger la red donde estas connectada podría estar previniendo que te conectes a los servicios relacionados con la billetera.",
  },
  "Onboarding": {
    "SkipA11y": "Omitir la introducción a la Billetera DigiCred", // *ACS*
  },
  "Preface": {
    "PrimaryHeading": "¿Es esta aplicación para ti?",
    "Paragraph1": "Por favor confirma.",
    "Confirmed": "He confirmado que esta aplicación es para mí.",
  },
  "Chat": {
    "OpenPresentation": "Abrir presentación",
    "ViewRequest": "Ver solicitud",
    "ViewOffer": "Ver oferta",
    "OpenItem": "Abrir",
    "UserYou": "Tú",
    "YouConnected": "Te has conectado con",
    "CredentialProposalSent": "envió una propuesta de credencial",
    "CredentialOfferReceived": "envió una oferta de credencial",
    "CredentialRequestSent": "envió una solicitud de credencial",
    "CredentialDeclined": "rechazó una oferta de credencial",
    "CredentialReceived": "recibió una credencial",
    "ProofRequestSent": "envió una solicitud de prueba",
    "ProofPresentationReceived": "te ha enviado información",
    "ProofRequestReceived": "recibió una solicitud de prueba",
    "ProofRequestRejected": "rechazó una solicitud de prueba",
    "ProofRequestRejectReceived": "rechazó una solicitud de prueba",
    "ProofRequestSatisfied": "compartió información",
  },
  "Verifier": {
    "UseVerifierCapability": "¿Usar la capacidad de Verificador?",
    "AcceptDevCredentials": "Aceptar credenciales no productivas?",
    "UseDevVerifierTemplates": "Usar plantillas de verificador de desarrollo?",
    "Toggle": "Alternar Capacidad de Verificador",
    "ToggleDevTemplates": "Alternar Plantillas de Desarrollo de Verificador",
    "ProcessingProof": "Un momento...",
    "ZeroKnowledgeProof": "Prueba de conocimiento cero",
    "Parameterizable": "Parametrizable",
    "RefreshQR": "Refrescar código QR",
    "GenerateNewQR": "Solicitar otra prueba",
    "BackToList": "Volver a la lista",
    "ShareLink": "Compartir enlace",
    "ScanQR": "Muestra este código QR a la otra persona",
    "ScanQRComment": "Después de que el código QR sea escaneado, se enviará una solicitud de prueba.",
    "InformationReceived": "Información recibida.",
    "InformationReceivedDetails": "Revisa la información a continuación.",
    "ProofVerificationFailed": "La verificación de la prueba falló",
    "ViewDetails": "Ver detalles",
    "HideDetails": "Ocultar detalles",
    "UseProofRequest": "Usar esta solicitud de prueba",
    "SendThisProofRequest": "Enviar esta solicitud de prueba",
    "SendProofRequest": "Enviar una Solicitud de Prueba",
    "EmptyList": "Tu billetera está vacía. Tus plantillas de solicitud de prueba se añadirán aquí.",
    "ShowTemplateUsageHistory": "Mostrar historial de uso",
    "RequestSent": "Solicitud de presentación enviada",
    "PresentationDeclined": "Solicitud de presentación rechazada",
    "PresentationReceived": "Presentación recibida",
    "PresentationFailed": "Presentación fallida",
    "ProofRequestRejected": "Solicitud de presentación rechazada",
    "PresentationFrom": "De",
    "PresentationState": "Estado",
    "ConnectionlessPresentation": "Anónimo",
    'TutorialStep1Title': 'Muestra este código QR a la otra persona',
    'TutorialStep1Description': 'Te conectarás con la otra persona. Ellos recibirán una solicitud de prueba.',
    "InvalidPredicateValueTitle": "Valor inválido para {{ predicate }}",
    "InvalidPredicateValueDetails": "Debe ser un número",
    "ConnectionLessLabel": "Anónimo",
  }
}
export default translation
